import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Link from "next/link";
import { getSession } from "@/lib/auth/session";
import HeaderCartInfo from "@/components/HeaderCartInfo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="border-b bg-card/50 backdrop-blur-sm">
            <div className="container mx-auto px-4 py-3 flex items-center justify-between">
              <Link href="/" className="font-semibold">TechNews</Link>
              
              {session ? (
                <div className="flex items-center gap-4">
                  <span className="text-sm">Xin chào, <strong>{session.tenNguoiDung}</strong></span>
                  <form action="/api/auth/logout" method="POST">
                    <button 
                      type="submit"
                      className="px-4 py-2 text-sm bg-destructive text-destructive-foreground rounded-md hover:bg-destructive/90"
                    >
                      Đăng xuất
                    </button>
                  </form>
                </div>
              ) : (
                <div className="flex gap-2">
                  <Link href="/login" className="px-4 py-2 text-sm border rounded-md hover:bg-accent">
                    Đăng nhập
                  </Link>
                  <Link href="/register" className="px-4 py-2 text-sm bg-primary text-primary-foreground rounded-md hover:bg-primary/90">
                    Đăng ký
                  </Link>
                </div>
              )}
            </div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}